# Generated by Django 6.1 on 2026-08-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='destination',
            field=models.CharField(max_length=100),
        ),
    ]
